### ISSUE TITLE
RPGgods 1.16.5

### ISSUE THREAD

**Issue by Orangejewce92** [skyjay1/RPG-Gods#10]
With Greek Fantasy installed and RPG Gods ( i even tried adding data pack)
The Scroll only displays Zeus i have no way of seeing other gods on scroll

**Comment by Orangejewce92** [comment]
hmm i see "i have not unlocked Knowledge about this deity " 
i am assume this is my issue? and Zeus is the only one i can see currently?

**Comment by skyjay1** [comment]
This is intentional. Some of the "perks" listed under Zeus will unlock the next deity.
