### ISSUE TITLE
Favor action appears to be completely broken.

### ISSUE THREAD

**Issue by kyragit** [skyjay1/RPG-Gods#4]
Title. I can't seem to get the favor action to trigger, despite showing up in the god's perk menu.

**Comment by skyjay1** [comment]
I need more details. Which favor action? What is the trigger (condition)? What is the required favor level?

**Comment by kyragit** [comment]
![image](https://user-images.githubusercontent.com/87741177/177013597-df837de0-7396-4b38-a0ba-292938298f34.png)
Here is my data currently. I've tried many different conditions, interact_block, interact_entity, random_tick, day, and none of them trigger the favor action. They work with other types of actions. I am trying to make it so that you can gain favor by shearing sheep, but I can't get it to trigger.

**Comment by skyjay1** [comment]
The action needs to specify the ID of the deity to grant favor. The wiki is missing this info, I will add it right away.
```
{
  "type": "favor",
  "id": "custom:gaia",
  "favor": 15
}
```
