### ISSUE TITLE
Using /reload doubles all of my custom god's perks, offerings, and sacrifices

### ISSUE THREAD

**Issue by kyragit** [skyjay1/RPG-Gods#5]
![image](https://user-images.githubusercontent.com/87741177/178073150-922ffbe0-1b9b-4f25-b2ce-381e79f5f63d.png)
![2022-07-08_14 30 21](https://user-images.githubusercontent.com/87741177/178073177-f9132f38-45d7-4e4f-8eb6-c7f1ff2ffb59.png)
If I use /reload again they stay doubled. I am using RPG Gods version 16.5.4. Quitting out the world and restarting fixes it.

**Comment by skyjay1** [comment]
Fixed in 19.2.1 and above
