### ISSUE TITLE
Favor action does not trigger perk cooldowns

### ISSUE THREAD

**Issue by kyragit** [skyjay1/RPG-Gods#7]
Creating a perk with the favor action does not seem to trigger the cooldown, it is always zero. Forge version 36.2.33, RPG Gods version 16.5.4.

**Comment by skyjay1** [comment]
Have you confirmed that the favor action runs successfully? If the action cannot run, it will not trigger cooldown.

**Comment by kyragit** [comment]
Yes, the favor adjusts accordingly, it just does not trigger a cooldown.

**Comment by skyjay1** [comment]
Can you post the perk JSON?

**Comment by kyragit** [comment]
Here, I just tested it again to make sure and yeah, it's still happening.
`{
  "icon": {
    "item": "minecraft:dirt"
  },
  "range": {
    "deity": "custom:gna",
    "minlevel": 0,
    "maxlevel": 10
  },
  "condition": [
    {
      "type": "random_tick"
    },
    {
      "type": "structure",
      "data": "minecraft:village"
    }
  ],
  "action": [
    {
      "type": "favor",
      "favor": 25,
      "id": "custom:gna"
    }
  ],
  "cooldown": 12000,
  "cooldown_category": "village_favor"
}`

**Comment by kyragit** [comment]
Is there any chance of getting this fixed for 1.16?

**Comment by skyjay1** [comment]
> Is there any chance of getting this fixed for 1.16?

No, I don't have time to maintain 1.16.x
