### ISSUE TITLE
BUG in thunder of Zeus. 

### ISSUE THREAD

**Issue by luquinhas53** [skyjay1/RPG-Gods#8]
I dont know how it started but i was playing for 2 days in my world with the mod in my modpack and suddenly when i invoked the gods (Zeus, being more directly) always get a thunder when I press SPACE. EVERYTIME with a certain cooldown. And this is getting very annoying. I already look at the entire mod looking for a solotiun thinking if my keyboard keys are in conflit but dont.

**Comment by skyjay1** [comment]
There is nothing in this mod that uses keybinds or relies on the player jumping, so I'm not sure what could cause this.
What is your favor level with Zeus? Which data pack are you using?
